export const HOME = "/";
export const TRELLO = '/trello';
export const TRELLO_QUIZ = '/trello/quiz'//basics
export const REQUIREMENTS = "/requirements"; //inheritance
export const REQUIREMENTS_QUIZ = "/requirements/quiz";
export const USECASES = "/usecases";//poly
export const USECASES_QUIZ = "/usecases/quiz";
export const TESTING = "/testing";//encap
export const TESTING_QUIZ = "/testing/quiz";